defaults:
    - override hydra/launcher: basic

# environment
# task: cluster_v2
task: alex_exp

exp_name: spread_exp

panelty: -200
time_step: 0.25
# world_name: "21_05"
# world_name: ???
save_name: ???
world_name: ???

# evaluation
checkpoint: ???
eval_episodes: 1000
eval_freq: 10




steps: 10_0000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
data_dir: ???

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5


# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: 5
num_enc_layers: 2
enc_dim: 256
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: ???
wandb_entity: ???
wandb_silent: false
disable_wandb: true
save_csv: true

# misc
save_video: false
save_agent: true
seed: ???

# convenience
work_dir: ???
task_title: ???
multitask: ???
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: 300
action_dims: ???
seed_steps: 1000
bin_size: ???